title: Hippogriff's Blog
author:
  name: hippogriff101
  email: hello@freddieyershon.co.uk

description: >
  Hi, I'm Freddie! Welcome to my Blog.


theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  # Force the Solarized Dark skin during local/dev builds.
  skin: solarized-dark

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/hippogriff101"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/hippogriff101/"