theme: minima
title: Hippogriff's Blog
author:
  name: Freddie Yershon
  email: hello@freddieyershon.co.uk

minima:
  # Force the Solarized Dark skin across the site.
  skin: solarized-dark

  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/hippogriff101"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/hippogriff101/"